export const APP_BOOTUP            = 'APP_BOOTUP';

export const SIGNIN_USER_REQUEST   = 'SIGNIN_USER_REQUEST';
export const SIGNIN_USER_SUCCESS   = 'SIGNIN_USER_SUCCESS';
export const SIGNIN_USER_ERROR     = 'SIGNIN_USER_ERROR';

export const SIGNUP_USER_REQUEST   = 'SIGNUP_USER_REQUEST';
export const SIGNUP_USER_SUCCESS   = 'SIGNUP_USER_SUCCESS';
export const SIGNUP_USER_ERROR     = 'SIGNUP_USER_ERROR';

export const SIGNOUT_USER_SUCCESS  = 'SIGNOUT_USER_SUCCESS';

// USERS
export const LOAD_USERS_REQUEST    = 'LOAD_USERS_REQUEST';
export const LOAD_USERS_SUCCESS    = 'LOAD_USERS_SUCCESS';
export const LOAD_USERS_ERROR      = 'LOAD_USERS_ERROR';

export const LOAD_ONE_USER_REQUEST = 'LOAD_ONE_USER_REQUEST';
export const LOAD_ONE_USER_SUCCESS = 'LOAD_ONE_USER_SUCCESS';
export const LOAD_ONE_USER_ERROR   = 'LOAD_ONE_USER_ERROR';

export const CREATE_USER_REQUEST   = 'CREATE_USER_REQUEST';
export const CREATE_USER_SUCCESS   = 'CREATE_USER_SUCCESS';
export const CREATE_USER_ERROR     = 'CREATE_USER_ERROR';

export const UPDATE_USER_REQUEST   = 'UPDATE_USER_REQUEST';
export const UPDATE_USER_SUCCESS   = 'UPDATE_USER_SUCCESS';
export const UPDATE_USER_ERROR     = 'UPDATE_USER_ERROR';

export const DELETE_USER_REQUEST   = 'DELETE_USER_REQUEST';
export const DELETE_USER_SUCCESS   = 'DELETE_USER_SUCCESS';
export const DELETE_USER_ERROR     = 'DELETE_USER_ERROR';